# -*- coding: utf-8 -*-
"""Ejercicios_practicas_pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z3JuPoi-1WD2nlAsFQLt4nGK3dMhUoPX

**# Ejecicios de prácticas con pandas**

**Nombre:** Jhon Freddy Alvino Lozano

**Datos del trabajo**

Supermarket Sales, publicado en Kaggle por Aung Pyae: 1000 ventas de tres sucursales durante tres
meses de 2019. El bloque siguiente carga los datos y normaliza los nombres de las columnas.
Ejecútelo tal como está: no es un ejercicio.

## Importación de librerías y preparación de los datos
"""

import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/plotly/datasets/master/supermarket_Sales.csv"

data = pd.read_csv(url)

# Renombrar algunas columnas
data = data.rename(columns={
    'Tax 5%': 'Tax',
    'Cost of goods sold': 'Cogs',
    'Gross margin percentage': 'Gross margin pct',
    'Customer stratification rating': 'Rating'
})

# Normalizar los nombres de las columnas
data.columns = (
    data.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
)

data.head()

"""Después de ejecutar el proceso, los nombres de las columnas quedan estandarizados en minúscula y sin espacios, facilitando su identificación y posterior procesamiento. Las columnas resultantes son: invoice_id, branch, city, customer_type, gender, product_line, unit_price, quantity, tax, total, date, time, payment, cogs, gross_margin_pct, gross_income y rating.

# **A. Conocer el DataFrame**

### Ejercicio 1

Complete la instrucción para conocer el número de filas y de columnas.
"""

print(data.shape)

"""**Respuesta:**

El primer número corresponde al número de registros o filas, que en este caso es **1.000**, y el segundo número corresponde al número de variables o columnas, que corresponde a **17**.

### Ejercicio 2

Muestre:

1. Los nombres de las columnas.
2. El tipo de dato de cada columna.
3. Las tres primeras ventas registradas.
"""

print("Nombres de las columnas:")
print(data.columns)

print("\nTipos de datos:")
print(data.dtypes)

print("\nTres primeras ventas:")
data.head(3)

"""# **B. Seleccionar datos**
Columnas, etiquetas y posiciones
### Ejercicio 3

Construya un subconjunto que contenga únicamente las siguientes columnas:

- `product_line`
- `quantity`
- `total`
"""

resultado = data[['product_line', 'quantity', 'total']]

resultado.head()

"""### Ejercicio 4

Antes de ejecutar el código, indique qué tipo de objeto devuelve cada línea. Después, compruebe el resultado.
"""

print(type(data['total']))
print(type(data[['total']]))

"""**Respuesta:**

La diferencia está en cómo se selecciona la columna:

**data['total']** devuelve una Serie de Pandas, es decir, una sola columna como una lista de datos.  
**data[['total']]** devuelve un DataFrame, manteniendo la estructura de una tabla.

La segunda opción utiliza doble corchete porque la columna total está dentro de una lista. Por eso, aunque se seleccione una sola columna, Pandas la mantiene como una tabla de dos dimensiones, con filas y columnas.

### Ejercicio 5

Las dos instrucciones siguientes deben mostrar la línea de producto de la fila con índice 7:

- La primera instrucción utiliza etiquetas mediante `loc`.
- La segunda instrucción utiliza posiciones mediante `iloc`.
"""

print(data.loc[7, 'product_line'])
print(data.iloc[7, 5])

"""**Respuesta:**

La segunda instrucción es más sensible a cambios en la estructura de la tabla, porque iloc selecciona los datos según la posición de la columna.

Si cambia el orden de las columnas, la posición 5 podría corresponder a una variable diferente. En cambio, loc permite seleccionar directamente utilizando el nombre de la columna, por lo que resulta más claro y seguro.

# **C. Filtrar filas**

### Ejercicio 6

Conserve únicamente las ventas de más de ocho unidades y cuente cuántas cumplen la condición.
"""

mascara = data['quantity'] > 8
resultado = data[mascara]

print("Cantidad de ventas:", resultado.shape[0])

"""### Ejercicio 7

Obtenga únicamente las ventas de la sucursal `C` cuyo total sea mayor de 300 USD.
"""

mascara = (
    (data['branch'] == 'C') &
    (data['total'] > 300)
)

resultado = data[mascara]

print("Dimensiones del resultado:", resultado.shape)
resultado.head()

"""### Ejercicio 8

La instrucción comentada falla porque el operador `or` no funciona para comparar directamente columnas de Pandas.

Reescriba el filtro utilizando una sola llamada que reciba la lista de líneas de producto.
"""

# Instrucción incorrecta:
#
# mascara = (
#     data['product_line'] == 'Food and beverages'
#     or 'Fashion accessories'
# )

mascara = data['product_line'].isin([
    'Food and beverages',
    'Fashion accessories'
])

resultado = data[mascara]

print("Cantidad de ventas:", resultado.shape[0])

"""### Ejercicio 9

Obtenga las ventas de las sucursales `A` y `C` cuyo total se encuentre entre 200 y 500 USD.

Muestre únicamente las siguientes columnas:

- `branch`
- `product_line`
- `quantity`
- `total`
"""

mascara = (
    data['branch'].isin(['A', 'C']) &
    data['total'].between(200, 500)
)

resultado = data.loc[
    mascara,
    ['branch', 'product_line', 'quantity', 'total']
]

resultado.head()

"""**Respuesta:**

La ventaja de utilizar loc es que permite filtrar las filas y seleccionar únicamente las columnas necesarias en una misma instrucción. Esto hace que el código sea más sencillo, claro y fácil de entender.

# **D. Crear información nueva**

### Ejercicio 10

Cree la columna `valor_unitario` dividiendo el total entre la cantidad.

Resuelva el ejercicio sin utilizar un ciclo `for`.
"""

data['valor_unitario'] = data['total'] / data['quantity']

print(data['valor_unitario'].head(3).round(2))

"""### Ejercicio 11

Clasifique las ventas de la siguiente manera:

- `volumen`: ventas de seis unidades o más.
- `menor`: ventas de menos de seis unidades.

"""

data['tipo_compra'] = np.where(
    data['quantity'] >= 6,
    'volumen',
    'menor'
)

print(data['tipo_compra'].value_counts())

"""**Respuesta:**

No fue necesario revisar las filas una por una, ya que Pandas y NumPy permiten aplicar una condición directamente sobre toda la columna.

Este tipo de procesamiento se conoce como operación vectorizada y permite realizar las operaciones de forma más rápida y sencilla.

# **E. Agrupar para responder preguntas**

### Ejercicio 12: ingreso generado por cada sucursal

**Nivel:** Básico

¿Cuánto ingreso genera cada sucursal?

Complete la agrupación que responde la pregunta.
"""

resumen = (
    data
    .groupby('branch')['total']
    .sum()
)

print(resumen.round(2))

"""### Ejercicio 13: facturas por método de pago

**Nivel:** Intermedio

¿Cuántas facturas registra cada método de pago?

Complete la columna sobre la que se cuenta y la operación correspondiente.
"""

resumen = (
    data
    .groupby('payment')['invoice_id']
    .count()
)

print(resumen)

"""**Respuesta:**

Cada fila muestra un medio de pago y cuántas facturas se registraron utilizando ese medio.

### Ejercicio 14: varias métricas por método de pago

**Nivel:** Avanzado

Determine para cada método de pago:

- Cuántas facturas registra.
- Cuántas unidades se vendieron.
- Cuánto ingreso generó.

Una sola agrupación debe entregar las tres métricas con nombres explícitos.
"""

resumen = (
    data
    .groupby('payment')
    .agg(
        facturas=('invoice_id', 'size'),
        unidades=('quantity', 'sum'),
        ingreso=('total', 'sum')
    )
    .reset_index()
)

print(resumen.round(2))

"""# **F. Integrar información**

### Ejercicio 15: agregar la zona de cada sucursal

**Nivel:** Intermedio

La tabla de ventas no indica en qué zona está cada sucursal. Esa información se encuentra en un catálogo independiente.

Integre la información conservando todas las ventas.
"""

sucursales = pd.DataFrame({
    'branch': ['A', 'B', 'C'],
    'zona': ['Centro', 'Norte', 'Sur']
})

sucursales

resultado = data.merge(
    sucursales,
    on='branch',
    how='left'
)

print("Dimensiones del resultado:", resultado.shape)

resultado[
    ['branch', 'city', 'zona', 'total']
].head()

"""# ¿Qué condición deben cumplir dos tablas para poder integrarse?

**Respuesta:**

Para integrar dos tablas, es necesario que ambas tengan al menos una columna en común que permita relacionar los registros de una tabla con los de la otra.

En este caso, la columna común es branch, que permite identificar y relacionar la sucursal correspondiente en ambas tablas. De esta manera, la información puede combinarse correctamente tomando esta columna como punto de relación.

# **# Ejercicio 16: sucursal líder entre los clientes Member**

**Nivel:** Avanzado

Considere únicamente las ventas de clientes de tipo `Member`.

Determine:

1. Qué sucursal genera el mayor ingreso total.
2. Cuál es su ticket promedio.
3. Cómo se compara ese ticket promedio con el de las otras sucursales.

El ticket promedio se calcula como:

\[
\text{Ticket promedio} =
\frac{\text{Ingreso total}}{\text{Número de facturas}}
\]
"""

# 1. Filtrar las ventas de clientes Member
member = data[
    data['customer_type'] == 'Member'
]

# 2. Agrupar por sucursal y calcular
#    el número de facturas y el ingreso total
resumen = (
    member
    .groupby('branch')
    .agg(
        facturas=('invoice_id', 'size'),
        ingreso=('total', 'sum')
    )
    .reset_index()
)

# 3. Calcular el ticket promedio
resumen['ticket_promedio'] = (
    resumen['ingreso'] /
    resumen['facturas']
)

# 4. Ordenar las sucursales de mayor a menor ingreso
resumen = resumen.sort_values(
    'ingreso',
    ascending=False
)

# 5. Mostrar el resultado
print(resumen.round(2))

"""**Conclusión**

La sucursal C registra el mayor ingreso entre los clientes de tipo Member, con un total de 56.881,28 y un ticket promedio de 336,58.

Además, presenta un ticket promedio superior al de las sucursales A y B, lo que indica que, en promedio, los clientes Member realizan compras de mayor valor en la sucursal C.

## Resumen de conceptos utilizados

Durante los ejercicios se utilizaron los siguientes conceptos de Pandas:

- `shape`: conocer las dimensiones de un DataFrame.
- `columns`: consultar los nombres de las columnas.
- `dtypes`: consultar los tipos de datos.
- `head()`: visualizar los primeros registros.
- `loc`: seleccionar utilizando etiquetas.
- `iloc`: seleccionar utilizando posiciones.
- `isin()`: comprobar si un valor pertenece a una lista.
- `between()`: filtrar valores dentro de un intervalo.
- `np.where()`: crear valores a partir de una condición.
- `groupby()`: agrupar registros.
- `agg()`: calcular varias métricas.
- `merge()`: integrar información de diferentes tablas.
- `sort_values()`: ordenar los datos.
- Operaciones vectorizadas para evitar ciclos innecesarios.

# **Autoevaluación rápida**

**1.** ¿Puedo distinguir entre una Series y un DataFrame?  

**Respuesta:** Sí. Ya entiendo que una Series es como una sola columna, mientras que un DataFrame es como una tabla completa, con filas y varias columnas.


**2.** ¿Puedo seleccionar filas y columnas usando loc?  

**Respuesta:** Sí. Puedo usar loc para buscar y seleccionar las filas y columnas que necesito, utilizando sus nombres o etiquetas.

**3.** ¿Puedo construir filtros con una o varias condiciones?

**Respuesta:** Sí. Puedo crear filtros con una condición o combinar varias condiciones para quedarme únicamente con los datos que necesito.

**4.** ¿Puedo usar groupby para responder una pregunta sobre los datos?  

**Respuesta:** Sí. Entiendo que groupby sirve para agrupar la información y después hacer cálculos, como contar, sumar o sacar promedios.

**5.** ¿Puedo explicar qué problema resuelve merge?  

**Respuesta:** Sí. merge me permite unir información de dos tablas cuando tienen una columna en común que sirve
"""